version: '3'

services:
  app:
    user: vscode
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 2.7
        NODE_VERSION: 14.16.1 
    volumes:
      - ..:/workspace:delegated
      - gem_cache:/usr/local/bundle/gems
      - $HOME/.ssh/:/home/vscode/.ssh/
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file: ../.env
    depends_on: 
      - db

  db:
    image: postgres:13
    restart: unless-stopped
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: linhdeptrai

volumes: 
  gem_cache:
  postgres_data:
