version: '3'

services:
  app:
    user: vscode
    restart: unless-stopped
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 2.7
        NODE_VERSION: 14.16.1 
    volumes:
      - ..:/workspace:delegated
      - gem_cache:/usr/local/bundle/gems
      - $HOME/.ssh/:/home/vscode/.ssh/
    command: /bin/sh -c "while sleep 1000; do :; done"
    env_file: ../.env
    depends_on: 
      - db

  db:
    image: mysql:8
    restart: unless-stopped
    volumes: 
      - mysql_data:/var/lib/mysql
    ports: 
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: linhdeptrai
      MYSQL_USER: linh
      MYSQL_PASSWORD: deptrai
      MYSQL_DATABASE: local

volumes: 
  gem_cache:
  mysql_data:
